require "graphql_activerecord_resolvers/extensions"
require "graphql_activerecord_resolvers/association"
require "graphql_activerecord_resolvers/association_tree"
require "graphql_activerecord_resolvers/version"

module GraphQLActiveRecordResolvers
end
